version: '3.7'

services:

  nystatecovid:
    build:
      context: .
    container_name: nycovid 
    restart: always
    image: nycovid:latest
  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./vscode:/config
      - /home/pi:/home/pi
    ports:
      - 8443:8443
    restart: unless-stopped