version: '3.7'

services:
  cvsCovidSelenium:
    container_name: cvsCovidSelenium 
    restart: always
    image: selenium/standalone-chrome-debug:3.141.59-20210311
    volumes:
      - /dev/shm:/dev/shm 
    ports:
      - 5901:5900
      - 4444:4444

 